runtime: php55
api_version: 0.5

handlers:
- url: /css
  static_dir: css

- url: /data/(.+\.php)$
  script: /data/\1

- url: /(.+\.php)$
  script: /\1

- url: /.*
  script: index.php

env_variables:
  CLOUDSQL_DSN:  mysql:dbname=pdsData;unix_socket=/cloudsql/isys1106-pds:australia-southeast1:sepm-assginment
<<<<<<< Updated upstream
=======
  # CLOUDSQL_DSN: mysql:host=localhost;dbname=pdsData
>>>>>>> Stashed changes
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: 123456
